import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
=======
import Navbar from './components/navbar';
>>>>>>> recovery-branch

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
<<<<<<< HEAD
  title: "Porfolio of Vincent",
=======
  title: "Vincent's Portfolio",
>>>>>>> recovery-branch
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
<<<<<<< HEAD
=======
          <Navbar />
>>>>>>> recovery-branch
        {children}
      </body>
    </html>
  );
}
